[package]
name = "bencodex"
version = "0.1.0"
authors = ["moreal <dev.moreal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"
num-bigint = "0.3"
