on: push
name: Test
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodule: recursive
      - uses: actions-rs/toolchain@v1.0.3
        with:
          toolchain: 1.49.0
      - run: cargo test
